version: '3.8'

services:
  deepxy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ALLOW_API_KEY: ${ALLOW_API_KEY}
      ALLOW_ORIGINS: ${ALLOW_ORIGINS}
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      DASHSCOPE_API_URL: ${DASHSCOPE_API_URL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_API_URL: ${OPENROUTER_API_URL}
      DEEPSEEK_MODEL: ${DEEPSEEK_MODEL}
      QWEN_MODEL: ${QWEN_MODEL}
      IS_ORIGIN_REASONING: ${IS_ORIGIN_REASONING}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
